#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01
IF="sefthy_wg"

start_service() {
    return 0
    procd_open_instance
    procd_set_param command /usr/bin/python /opt/sefthy-wrt-wh/app.py
    procd_set_param respawn

    procd_set_param interface "$IF"
    procd_add_reload_interface_trigger "$IF"

    procd_set_param stdout 0
    procd_set_param stderr 1

    procd_close_instance
}

stop_service() {
    pid=$(pgrep -f "sefthy-wrt-wh")
    [ -n "$pid" ] && kill $pid
}

reload_service() {
    stop
    sleep 1
    start
}