#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01

start_service() {
    return 0
    ip link show dev sefthy_wg >/dev/null || return 0
    procd_open_instance "sefthy-wrt-wh"
    procd_set_param command /usr/bin/python /opt/sefthy-wrt-wh/app.py
    procd_set_param respawn

    procd_set_param stdout 0
    procd_set_param stderr 1

    procd_close_instance
}

stop_service() {
    pid=$(pgrep -f "sefthy-wrt-wh")
    [ -n "$pid" ] && kill $pid
}

service_triggers() {
    procd_add_interface_trigger "interface.*" "sefthy_wg" /etc/init.d/sefthy-wrt-wh restart
}